name: Plugin
version: ${project.version}
main: com.shrigorevich.Plugin
api-version: 1.17
commands:
  auth:
    description: "Auth"
    aliases: [ authorization ]
  village:
    description: "Village management"
    aliases: [ reg ]
  cells:
    description: "Cell manager"
    aliases: [ c ]
  matrix:
    description: "Create matrix for village"
    aliases: []
  mob:
    description: "mob spawner"
    aliases: []

