name: Plugin
version: ${project.version}
main: com.shrigorevich.Plugin
api-version: 1.16
commands:
  auth:
    description: "Auth"
    aliases: [ authorization ]
  village:
    description: "Village management"
    aliases: [ reg ]
  cells:
    description: "Cell manager"
    aliases: [ c ]

